In [ ]:
import pandas as pd
import plotly.express as px

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving IPL_Matches_2008_2022.csv to IPL_Matches_2008_2022.csv

In [ ]:
import pandas as pd

df = pd.read_csv('IPL_Matches_2008_2022.csv')
df.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [ ]:
print("Missing Values")

print(df.isnull().sum())

df.drop_duplicates(inplace=True)

print("After Removing Duplicates")
print(df.shape)

Missing Values
ID                   0
City                51
Date                 0
Season               0
MatchNumber          0
Team1                0
Team2                0
Venue                0
TossWinner           0
TossDecision         0
SuperOver            4
WinningTeam          4
WonBy                0
Margin              18
method             931
Player_of_Match      4
Team1Players         0
Team2Players         0
Umpire1              0
Umpire2              0
dtype: int64
After Removing Duplicates
(950, 20)

In [ ]:
total_matches = len(df)
total_teams = df['Team1'].nunique()
total_venues = df['Venue'].nunique()

top_team = df['WinningTeam'].value_counts().idxmax()

print("Total Matches:", total_matches)
print("Total Teams:", total_teams)
print("Total Venues:", total_venues)
print("Most Successful Team:", top_team)

Total Matches: 950
Total Teams: 18
Total Venues: 49
Most Successful Team: Mumbai Indians

In [ ]:
fig = px.histogram(df,x='Season',
title='Matches Per Season')

fig.show()

In [ ]:
wins = df['WinningTeam'].value_counts()

fig = px.bar(
x=wins.index,
y=wins.values,
title='Team Wins'
)

fig.show()

In [ ]:
fig = px.pie(
df,
names='TossDecision',
title='Toss Decisions'
)

fig.show()

In [ ]:
top_players = df['Player_of_Match'].value_counts().head(10)

fig = px.bar(
x=top_players.index,
y=top_players.values,
title='Top Players'
)

fig.show()

In [ ]:
top_venues = df['Venue'].value_counts().head(10)

fig = px.bar(
x=top_venues.index,
y=top_venues.values,
title='Top Venues'
)

fig.show()

In [ ]:
season = int(input("Enter Season: "))

filtered = df[df['Season']==season]

filtered.head()

Enter Season: 8

Empty DataFrame
Columns: [ID, City, Date, Season, MatchNumber, Team1, Team2, Venue, TossWinner, TossDecision, SuperOver, WinningTeam, WonBy, Margin, method, Player_of_Match, Team1Players, Team2Players, Umpire1, Umpire2]
Index: []